services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      DB_HOST: ${DB_HOST_CONTAINER}
    volumes:
      - ./server/app:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT_CONTAINER}" 

  # parser:
  #   build:
  #     context: ./parser
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./parser/.env
  #   volumes:
  #     - ./parser/app:/app
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
