// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	ReleaseYear int32   `json:"releaseYear"`
}

type MovieInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	ReleaseYear int32   `json:"releaseYear"`
}

type Mutation struct {
}

type Query struct {
}
